
enum opcode_enum{
  _0NNN = 1,
  _00E0,
  _00EE,
  _1NNN,
  _2NNN,
  _3XNN,
  _4XNN,
  _5XY0,
  _6XNN,
  _7XNN = 10,
  _8XY0,
  _8XY1,
  _8XY2,
  _8XY3,
  _8XY4,
  _8XY5,
  _8XY6,
  _8XY7,
  _8XYE,
  _9XY0 = 20,
  _ANNN,
  _BNNN,
  _CXNN,
  _DXYN,
  _EX9E,
  _EXA1,
  _FX07,
  _FX0A,
  _FX15,
  _FX18 = 30,
  _FX1E,
  _FX29,
  _FX33,
  _FX55,
  _FX65 = 35
};

const char* opcode_array[36] = {
  "",
  "0NNN",
  "00E0",
  "00EE",
  "1NNN",
  "2NNN",
  "3XNN",
  "4XNN",
  "5XY0",
  "6XNN",
  "7XNN",
  "8XY0",
  "8XY1",
  "8XY2",
  "8XY3",
  "8XY4",
  "8XY5",
  "8XY6",
  "8XY7",
  "8XYE",
  "9XY0",
  "ANNN",
  "BNNN",
  "CXNN",
  "DXYN",
  "EX9E",
  "EXA1",
  "FX07",
  "FX0A",
  "FX15",
  "FX18",
  "FX1E",
  "FX29",
  "FX33",
  "FX55",
  "FX65"
};

const char* opcode_description_array[36] = {
  "",
  "Calls RCA 1802 program at address NNN.",
  "Clears the screen.",
  "Returns from a subroutine.",
  "Jumps to address NNN.",
  "Calls subroutine at NNN.",
  "Skips the next instruction if VX equals NN.",
  "Skips the next instruction if VX doesn't equal NN.",
  "Skips the next instruction if VX equals VY.",
  "Sets VX to NN.",
  "Adds NN to VX.",
  "Sets VX to the value of VY.",
  "Sets VX to VX or VY.",
  "Sets VX to VX and VY.",
  "Sets VX to VX xor VY.",
  "Adds VY to VX. VF is set to 1 when there's a carry, and to 0 when there isn't.",
  "VY is subtracted from VX. VF is set to 0 when there's a borrow, and 1 when there isn't.",
  "Shifts VX right by one. VF is set to the value of the least significant bit of VX before the shift.",
  "Sets VX to VY minus VX. VF is set to 0 when there's a borrow, and 1 when there isn't.",
  "Shifts VX left by one. VF is set to the value of the most significant bit of VX before the shift.",
  "Skips the next instruction if VX doesn't equal VY.",
  "Sets I to the address NNN.",
  "Jumps to the address NNN plus V0.",
  "Sets VX to a random number, masked by NN.",
  "Sprites stored in memory at location in index register (I), maximum 8bits wide. Wraps around the screen. If when drawn, clears a pixel, register VF is set to 1 otherwise it is zero. All drawing is XOR drawing",
  "Skips the next instruction if the key stored in VX is pressed.",
  "Skips the next instruction if the key stored in VX isn't pressed.",
  "Sets VX to the value of the delay timer.",
  "A key press is awaited, and then stored in VX.",
  "Sets the delay timer to VX.",
  "Sets the sound timer to VX.",
  "Adds VX to I.",
  "Sets I to the location of the sprite for the character in VX. Characters 0-F (in hexadecimal) are represented by a 4x5 font.",
  "Stores the Binary-coded decimal representation of VX, with the most significant of three digits at the address in I, the middle digit at I plus 1, and the least significant digit at I plus 2.",
  "Stores V0 to VX in memory starting at address I.",
  "Fills V0 to VX with values from memory starting at address I."
};
